homefinder/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include,url

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^homesapp/',include('homesapp.urls')),
]

homesapp/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include,url
from .import views

urlpatterns = [
    #/homesapp
    url(r'^$', views.IndexView.as_view(),name='index'),
    #/homesapp/1
    url(r'^(?P<pk>[0-9]+)/$',views.LocationView.as_view(), name='property'),
    #/homesapp/1/2
    url(r'^([0-9]+)/(?P<pk>[0-9]+)/$',views.PropertyDetail.as_view(),name='propertyview'),
]

homesapp/models.py
from django.db import models

# Create your models here.

class Location(models.Model):
    location_name = models.CharField(max_length = 200)
    location_type = models.CharField(max_length = 200)

    def __str__(self):
        return self.location_name

class Property(models.Model):
    location = models.ForeignKey(Location,on_delete = models.CASCADE)
    property_name = models.CharField(max_length = 200)
    area = models.CharField(max_length = 200)

    age = models.CharField(max_length = 200)
    price = models.CharField(max_length = 200)
    direction = models.CharField(max_length = 200)
    floor = models.CharField(max_length = 200)
    postadd = models.CharField(max_length = 200)
    image_url = models.CharField(max_length = 500)

    lat_field = models.CharField(max_length = 200)
    long_field = models.CharField(max_length = 200)

    def __str__(self):
        return self.property_name

homesapp/views.py
from django.shortcuts import render
from django.views import generic
from .models import Location,Property
# Create your views here.

class IndexView(generic.ListView):
    template_name = 'homesapp/index.html'

    def get_queryset(self):
        return Location.objects.all()

class LocationView(generic.DetailView):
    model = Location
    template_name = 'homesapp/locationview.html'

class PropertyDetail(generic.DetailView):
    model = Property
    template_name = 'homesapp/propertyview.html'

homesapp/templates/homesapp/base.html
<html>
    <head>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    </head>
    <body>
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand" href="/homesapp/">Property Arena</a>
                </div>
                
                <ul class="nav navbar-nav">
                    <li class="active"><a href="/homesapp/">Home</a></li>
                    <li><a href="#">Page 1</a></li>
                    <li><a href="#">Page 2</a></li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                        <li><a href="#">Sign Up</a></li>
                        <li><a href="#">Login</a></li>
                    </ul>
    


            </div>

        </nav>
    {% block body %}
    {% endblock %}
    </body>


</html>

homesapp/templates/homesapp/index.html
{% extends 'homesapp/base.html' %}


<html>
    <head>

    </head>
    {% block body %}
    <body>
        <div class="container">
            <div class="jumbotron">
                <h1>Property Arena</h1>
                <p>Find the best properties across all locations</p>
            </div>
        </div>

        <center><h1>Select your location</h1></center>
            <div class="panel-group">
                <div class="panel panel-default">
                    <div class="panel-heading">Locations</div>
                    {% for location in object_list %}
                     <div class="panel-body"> <a href="/homesapp/{{location.id}}">{{location.location_name}}</a><br>
                     </div>  
                    {% endfor %}
                </div>
            </div>

    </body>
    {% endblock %}
</html>

homesapp/templates/homesapp/locationview.html
{% extends 'homesapp/base.html' %}


{% block body %}


<html>
    <head>

    </head>
    <body>
        <div class="col-md-1">

        </div>

        <div class="col-md-8">
            <h1>Properties in {{location.location_name}}</h1>

            <div class="panel-group">
            {% for place in location.property_set.all %}
                <div class="panel panel-primary">
                    <div class="panel-heading">{{place.property_name}}</div>
                    <div class="panel-body">
                        <div class="col-md-4">
                            <img src="{{place.image_url}}" height="200" width="200">
                        </div>
                        <div class="col-md-6">
                            <table class="table">
                                <tbody>
                                    <tr>
                                        <td><label><b>Area SQFT</b></label></td>
                                        <td>{{place.area}}</td>
                                    </tr>
                                    <tr>
                                        <td><label><b>Price</b></label></td>
                                        <td>{{place.price}}</td>
                                    </tr>
                                    <tr>
                                        <td><label><b>No of Floors</b></label></td>
                                        <td>{{place.floor}}</td>
                                    </tr>
                                    <tr>
                                        <td><label><b>Address</b></label></td>
                                        <td>{{place.postadd}}</td>
                                    </tr>
                                    <tr>
                                        <td>
                                        </td>
                                        <td>
                                        </td>
                                        <td><a class="btn btn-success" href="/homesapp/{{location.id}}/{{place.id}}">View Details</a></td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            {% endfor %}
            </div>
        </div>
    </body>


</html>


{% endblock %}

homesapp/templates/homesapp/propertyview.html
{% extends 'homesapp/base.html' %}

{% block body %}

<html>
    <head>
            <style>
                /* Set the size of the div element that contains the map */
                #map {
                height: 400px;  /* The height is 400 pixels */
                width: 100%;  /* The width is the width of the web page */
                }
            </style>
    </head>
    <body>
        <div class="row">
            <div class="col-md-1">

            </div>

            <div class="col-md-3">
                <div class="thumbnail">
                    <img src="{{property.image_url}}" height-"420" width="420">
                    <div class="caption">
                        <p>{{property.property_name}}</p>
                    </div>
                </div>
            </div>

            <div class="col-md-8">
                <div class="container">
                    <div class="panel-group">
                        <div class="panel panel-primary">
                            <div class="panel-heading">Property Detail's</div>
                            <div class="panel-body">
                                <table class="table">
                                    <tbody>
                                        <tr>
                                            <td>
                                                <label><b>Area SQFT</b></label>
                                            </td>
                                            <td>
                                                {{property.area}}
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label><b>Price</b></label>
                                            </td>
                                            <td>
                                                 {{property.price}}
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label><b>Age</b></label>
                                            </td>
                                            <td>
                                                {{property.age}}
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label><b>Direction</b></label>
                                            </td>
                                            <td>
                                                {{property.direction}}
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label><b>No of Floors</b></label>
                                            </td>
                                            <td>
                                                {{property.floor}}
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label><b>Address</b></label>
                                            </td>
                                            <td>
                                                {{property.postadd}}
                                            </td>
                                        </tr>                  
                                </table>
                            </div>
                        </div>   
                    </div>
                </div>
            </div>

        </div>


<!--map starts here-->        
            <div class="col-md-8">
                <div class="thumbnail">
                    <h3>Location</h3>
                    <div id="map"></div>
                        <script>
                            // Initialize and add the map
                            function initMap() {
                                // The location of Uluru
                                var uluru = {lat: {{property.lat_field}}, lng: {{property.long_field}}};
                                // The map, centered at Uluru
                                var map = new google.maps.Map(document.getElementById('map'), {zoom: 15, center: uluru});
                                // The marker, positioned at Uluru
                                var marker = new google.maps.Marker({position: uluru, map: map});
                            }
                        </script>
                <!--Load the API from the specified URL
                 * The async attribute allows the browser to render the page while the API loads
                 * The key parameter will contain your own API key (which is not needed for this tutorial)
                * The callback parameter executes the initMap() function-->
            <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAqypZrrSbgMkhF7FGZ5iG7mC5hovk26pQ&callback=initMap">
            </script>
                </div>

            </div>

    </body>
</html>


{% endblock %}